image:
  repository: iris-api
  tag: dev
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

serviceMonitor:
  enabled: true
  interval: 15s
  labels:
    release: "monitoring"
