{
 "title": "Iris API",
 "tags": [
  "mlops",
  "sre",
  "demo"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Predict Throughput (5m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(requests_total{endpoint=\"/predict\"}[5m]))",
     "legendFormat": "reqs/5m"
    }
   ]
  },
  {
   "title": "Prediction Errors (5m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(predict_errors_total[5m]))",
     "legendFormat": "errors/5m"
    }
   ]
  },
  {
   "title": "p95 Latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket{endpoint=\"/predict\"}[5m])) by (le))",
     "legendFormat": "p95 /predict"
    }
   ]
  }
 ]
}