apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iris-api.fullname" . }}
  labels:
    {{- include "iris-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "iris-api.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "iris-api.name" . }}
    spec:
      containers:
        - name: iris-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
